### ISSUE TITLE
Definição do README do projeto

### ISSUE THREAD

**Issue by mateusrovedaa** [aztecweb/lista-de-compras#1]
## Descrição
O arquivo README de um projeto é o cartão de visitas do projeto para a comunidade ou até mesmo serve como um guia interno de como utilizar determinada ferramenta ou o que precisa para o projeto funcionar. Basicamente, o README é composto por todas informações úteis de um projeto desde:
- O que é o projeto
- Qual o objetivo
- Como executar
- Como contribuir
- Time ou pessoas que colaboraram e estão envolvidas no projeto
- Licença
- Demais informações que possam ser úteis

A Rocketseat fez um excelente post contando um pouco mais desse arquivo, então recomendo a leitura para entender ainda um pouco mais sobre o que é e qual a finalidade desse importante arquivo para o projeto.

[O que é README e por que ele é tão importante?](
https://blog.rocketseat.com.br/o-que-e-readme-e-porque-e-tao-importante/)

## Objetivo
Definir e discutir quais informações farão parte do README deste projeto. Além disso, precisamos também debater sobre como deixar este arquivo tão importante bem organizado, facilitando o entendimento de pessoas que não conhecem sobre o projeto, auxiliando quem quer contribuir e mantendo informações importantes para a execução e utilização.

Anexado a essa issue se encontram os arquivos que foram disponibilizados pelo site devChallenges como artefatos iniciais.

## Artefatos
- [Artefatos iniciais devChallenges](https://github.com/aztecweb/lista-de-compras/files/8665861/shoppingify-master.zip)
- [Link do figma com os designs](https://www.figma.com/file/kX8FNpYFVLI4ivuEQ6yGgS/Shopping-List?node-id=0%3A1)
- [Link do projeto no DevChallenges](https://devchallenges.io/challenges/mGd5VpbO4JnzU6I9l96x)

**Comment by marcosvile** [comment]
##Sugestão: criar um quarto kaban na aba projetos, criar e atribuir task com os tópicos da descrição da issue:

O que é o projeto

Qual o objetivo

Como executar

Como contribuir

Time ou pessoas que colaboraram e estão envolvidas no projeto

Licença

Demais informações que possam ser úteis


# Cada um lhe seria atribuído uma task para criar a descrição de cada tópico a ser consolidado depois no readme.

**Comment by marcosvile** [comment]
~~ Sugestão: criar um quarto kaban na aba projetos, criar e atribuir task com os tópicos da descrição da issue:

O que é o projeto

Qual o objetivo

Como executar

Como contribuir

Time ou pessoas que colaboraram e estão envolvidas no projeto

Licença

Demais informações que possam ser úteis


~~ Cada um lhe seria atribuído uma task para criar a descrição de cada tópico a ser consolidado depois no readme.

**Comment by marcosvile** [comment]
### Sugestão: criar um quadro kaban na aba projetos, criar e atribuir cards com tasks com os tópicos da descrição da issue:

- O que é o projeto

- Qual o objetivo

- Como executar

- Como contribuir

- Time ou pessoas que colaboraram e estão envolvidas no projeto

- Licença

- Demais informações que possam ser úteis

###   Cada um lhe seria atribuído uma task para criar a descrição de cada tópico a ser consolidado depois no readme.

**Comment by aldair-meneses** [comment]
Alguns tópicos que são interessantes estar no README:
* Informações detalhadas sobre o projeto.
* Área com algumas perguntas protnas e respostas prontas sobre o projeto. 
* Instruções sobre como usar 
* Links/seções para navegar com mais facilidade pela estrutura do repositório
* Imagem ilustrativa sobre o projeto.

**Comment by mateusrovedaa** [comment]
Tópicos que acho interessante termos no README:

- O que é o projeto
- Qual o objetivo
- Como executar
- Como contribuir
- Time ou pessoas que colaboraram e estão envolvidas no projeto
- Licença
- Demais informações que possam ser úteis

O que acho que pode ser um bônus mas que não precisam ser feito agora:

- FAQ
- Links/seções para navegar com mais facilidade pela estrutura do repositório
- Imagem ilustrativa sobre o projeto.

**Comment by mateusrovedaa** [comment]
## Definições sobre a criação do README:
- O processo para pull requests será o seguinte: Cada um criará um fork do projeto e desenvolverá no seu projeto as mudanças necessárias. Após isso, será feito pull's requests para a branch criada para essa issue. Com base nas PRs realizadas, avaliaremos quais aceitar e o que mudar para enviarmos posteriormente para a branch principal do projeto;
- Cada um desenvolverá o seu arquivo README e, em live (encontros), faremos uma análise do que faz sentido agregar no README oficial do projeto.

## Tópicos que precisam estar no README
- O que é o projeto
- Qual o objetivo
- Como executar
- Como contribuir
- Time ou pessoas que colaboraram e estão envolvidas no projeto

**Comment by marcosvile** [comment]
**Para a criação do readme, estou me guiando sobre as marcações Markdown pelo conteúdo do link:**

https://docs.pipz.com/central-de-ajuda/learning-center/guia-basico-de-markdown#open

**Comment by marcosvile** [comment]
Pensando no desenvolvimento do projeto e completar as informações no readme, estou lendo sobre o licenciamento do projeto na documentação do github:

https://docs.github.com/pt/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

e pelo conteúdo:

http://www.gnu.org/licenses/quick-guide-gplv3.html

o que acham?
