### ISSUE TITLE
Definir framework de front-end

### ISSUE THREAD

**Issue by edpittol** [aztecweb/lista-de-compras#20]
Precisamos definir qual framework será utilizado para o desenvolvimento front-end do projeto. Como vamos utilizar o storybook como documentação dos componente, a escolha deve estar relacionada com os [frameworks suportados](https://storybook.js.org/docs/react/api/new-frameworks#:~:text=Storybook%20is%20architected%20to%20support%20diverse%20web%20frameworks%2C%20including%20React%2C%20Vue%2C%20Angular%2C%20Web%20Components%2C%20Svelte%2C%20and%20over%20a%20dozen%20others.) por ele.

**Comment by marcosvile** [comment]
### Listagem dos frameworks suportados:

| Framework                                                      | Demo                                                                                                                                                                                               |                                                                                                                                                      |
| -------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------- |
| [React](app/react)                                             | [![Storybook demo](https://img.shields.io/npm/v/@storybook/react/latest?style=flat-square&color=blue&label)](https://storybookjs.netlify.com/official-storybook/?path=/story/*)                  | [![React](https://img.shields.io/npm/dm/@storybook/react?style=flat-square&color=eee)](app/react)                                                    |
| [Vue](app/vue)                                                 | [![Storybook demo](https://img.shields.io/npm/v/@storybook/vue/latest?style=flat-square&color=blue&label)](https://storybookjs.netlify.com/vue-kitchen-sink/)                                    | [![Vue](https://img.shields.io/npm/dm/@storybook/vue?style=flat-square&color=eee)](app/vue)                                                        |
| [Angular](app/angular)                                         | [![Storybook demo](https://img.shields.io/npm/v/@storybook/angular/latest?style=flat-square&color=blue&label)](https://storybookjs.netlify.com/angular-cli/)                                     | [![Angular](https://img.shields.io/npm/dm/@storybook/angular?style=flat-square&color=eee)](app/angular)                                            |
| [Web components](app/web-components)                           | [![Storybook demo](https://img.shields.io/npm/v/@storybook/web-components/latest?style=flat-square&color=blue&label)](https://storybookjs.netlify.com/web-components-kitchen-sink/)              | [![Svelte](https://img.shields.io/npm/dm/@storybook/web-components?style=flat-square&color=eee)](app/web-components)                               |
| [React Native](https://github.com/storybookjs/react-native)    | -                                                                                                                                                                                                  | [![React Native](https://img.shields.io/npm/dm/@storybook/react-native?style=flat-square&color=eee)](https://github.com/storybookjs/react-native)  |
| [HTML](app/html)                                               | [![Storybook demo](https://img.shields.io/npm/v/@storybook/html/latest?style=flat-square&color=blue&label)](https://storybookjs.netlify.com/html-kitchen-sink/)                                  | [![HTML](https://img.shields.io/npm/dm/@storybook/html?style=flat-square&color=eee)](app/html)                                                     |
| [Ember](app/ember)                                             | [![Storybook demo](https://img.shields.io/npm/v/@storybook/ember/latest?style=flat-square&color=blue&label)](https://storybookjs.netlify.com/ember-cli/)                                         | [![Ember](https://img.shields.io/npm/dm/@storybook/ember?style=flat-square&color=eee)](app/ember)                                                  |
| [Svelte](app/svelte)                                           | [![Storybook demo](https://img.shields.io/npm/v/@storybook/svelte/latest?style=flat-square&color=blue&label)](https://storybookjs.netlify.com/svelte-kitchen-sink/)                              | [![Svelte](https://img.shields.io/npm/dm/@storybook/svelte?style=flat-square&color=eee)](app/svelte)                                               |
| [Preact](app/preact)                                           | [![Storybook demo](https://img.shields.io/npm/v/@storybook/preact/latest?style=flat-square&color=blue&label)](https://storybookjs.netlify.com/preact-kitchen-sink/)                              | [![Preact](https://img.shields.io/npm/dm/@storybook/preact?style=flat-square&color=eee)](app/preact)                                               |
| [Marionette.js](https://github.com/storybookjs/marionette)     | -                                                                                                                                                                                                  | [![Marionette.js](https://img.shields.io/npm/dm/@storybook/marionette?style=flat-square&color=eee)](https://github.com/storybookjs/marionette)     |
| [Android, iOS, Flutter](https://github.com/storybookjs/native) | [![Storybook demo](https://img.shields.io/npm/v/@storybook/native/latest?style=flat-square&color=blue&label)](https://storybookjs.github.io/native/@storybook/native-flutter-example/index.html) | [![Native](https://img.shields.io/npm/dm/@storybook/native?style=flat-square&color=eee)](https://github.com/storybookjs/native)  


fonte: https://github.com/storybookjs/storybook#supported-frameworks


Para melhor estudar o framework a ser utilizado, vamos levantar pontos a considerar dos padrões de projeto? ex. Será apenas webapp ou multi device? Culturalmente qual a curva de aprendizagem e desenvolvimento de cada framework? (se possível mensurar), acredito que são esses os pontos iniciais a discutir. Quais os requisitos iniciais do projeto em relação a adequação de cada framework?

**Comment by edpittol** [comment]
@marcosvile O projeto será um webapp e a curva de aprendizado entre os frameworks são similares. Pelo requisito ser um webapp, precisa ser algum framework JS e que também ajuda na criação de componentes.

Não entendi muito bem sobre o que fala dos requisitos iniciais. Mas basicamente o que precisamos de início é desenhar alguns componentes dentro do Storybook.

**Comment by mblithium** [comment]
Seria interessante nós utilizarmos o **React JS** mesmo, visto que tem vasta documentação para aprender esse framework, além de ser bastante conhecido e usado. Acredito que tanto o **React**, **Angular** ou **Vue** necessitam que pelo menos aprenda a base de **HTML5**, **CSS3** e **JS**.

Agora mais pelo lado do setup inicial do projeto, usar o **yarn** (package manager, em vez do **NPM**) e pelo que andei pesquisando um tal de "**Vite**" que é um _"Frontend Tooling"/"Boilerplate"_ que aparentemente é mais compacto e mais otimizado do que o geralmente utilizado "**create-react-app**", tem um post no blog do próprio Storybook falando dele [aqui](https://storybook.js.org/blog/storybook-for-vite/). Testei os dois com o projeto React e com o Storybook, o Vite não cria tantas dependências. Talvez a gente precise decidir, antes de tudo, se vai utilizar o **JavaScript "Vanilla"** ou um **TypeScript** (não sei muito bem como funciona, mas pelo que entendi pode utilizar o JS normal nele com um pouco mais de recursos opcionais de tipagem, porém vi relatos de pessoas dizendo que certas dependências não serem possíveis de importar por não ter o suporte para ele).

**Comment by edpittol** [comment]
Conforme conversamos no encontro, fica definido o uso do React como framework, ops, biblioteca, de front-end.
