### ISSUE TITLE
TypeScript ou JavaScript

### ISSUE THREAD

**Issue by RaisaSampaio** [aztecweb/lista-de-compras#24]
Precisamos decidir se vamos utilizar uma linguagem fortemente tipada, o TypeScript ou uma linguagem fracamente tipada, o JavaScript.

Materiais de apoio:
* [JavaScript ou TypeScript](https://www.alura.com.br/artigos/javascript-ou-typescript?utm_source=awin&utm_medium=site&utm_term=101248&awc=23465_1660348813_b09432bc1679a3196595430a58123c47)

**Comment by IgorVinoski** [comment]
Não vejo problemas em iniciarmos utilizando TypeScript.
Acredito que a barreira para um iniciente entre inicar com TypeScript e JavaScript é a mesma.

**Comment by mblithium** [comment]
Ao meu ver, para quem está começando em desenvolvimento web, o TypeScript (TS) pode ser uma etapa adicional que pode confundir a pessoa, que ainda não sabe como funciona o JavaScript (JS). Digamos que ele ele é um interpretador que faz a transpilação para o código JS e que adiciona a declaração e validação de tipos (e outras funcionalidades extras), que no final, tudo vira linguagens que o navegador entenda. Não que seja uma coisa que fique muito difícil, mas talvez possa confundir um pouco. Mas por outro lado, é possível usar TS sem usar as funcionalidades dele por enquanto, o problema pode ser os linters, além de ser uma boa a utilização do TS no mercado, que já estaria aprendendo essa ferramenta + o JS. Resumidamente, para mim, seria interessante a utilização do TypeScript sem problemas, mas para quem está tentando começar agora, pode ser que confunda um pouco.

**Comment by marcosvile** [comment]
Segue um artigo no Alura [JavaScript ou TypeScript](https://www.alura.com.br/artigos/javascript-ou-typescript?gclid=Cj0KCQjw94WZBhDtARIsAKxWG-9GUNfmez1pp0iuDv9oZP0YWuTJYgnpJQKXosTz9kPRB7qJTwVGAHkaAnqYEALw_wcB) uma **breve** comparação sobre as linguagens, com base na interpretação desse artigo, não vejo problemas em iniciar com JavaScript pensando nas opção que podemos incorporar o TypeScript no deccorrer do projeto.

**Comment by edpittol** [comment]
Ficou definido o uso de TypeScript. É uma linguagem que está bem estável e traz mais confiabilidade para o ecossistema JavaScript. Está ganhando mercado. Portanto faz muito sentido utilizarmos ela.
