### ISSUE TITLE
Criar quadro Kanban para organizar as issues

### ISSUE THREAD

**Issue by mateusrovedaa** [aztecweb/lista-de-compras#3]
## Descrição
Um quadro Kanban servirá para nos auxiliar a controlar as issues que estão para serem feitas, que estão sendo feitas ou que já foram terminadas. Isso nos dará uma visão melhor do todo e do como anda o projeto.

![image](https://user-images.githubusercontent.com/22747307/168486880-26a59dd6-4182-4c35-aeae-1ef29453d824.png)

## Objetivo
Criar um quadro Kanban para melhor visualizarmos as issues e o andamento delas.
@edpittol Precisaremos de você nessa issue, pois pelo o que entendi, o quadro precisa ser criado na organização.

## Artefatos
[Criar quadros de projetos](https://docs.github.com/pt/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards#creating-and-viewing-project-boards)
[Sobre quadros de projetos](https://docs.github.com/pt/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards)
[Sobre Kanban](https://kanbanize.com/pt/recursos-kanban/primeiros-passos/o-que-e-quadro-kanban)

**Comment by edpittol** [comment]
[Quadro de Kanban](https://github.com/aztecweb/lista-de-compras/projects/1) criado.

Deixei com configurações simples. É possível editar nome, descrição e alterar as colunas. Podemos ir mexendo conforme o projeto evolui e surjam novas necessidades.

Precisamos testar o que os colaboradores do projeto possuem de permissão para fazer dentro do quadro. É importante que exista uma liberdade para isso.

Deixei lá também os cartões que vêm automático quando um quadro é criado para que possam aprender algo sobre o uso do quadro dentro do GitHub.

/cc @aztecweb/comunidade-aztec

**Comment by mateusrovedaa** [comment]
Adicionei as issues ao projeto, deixando ainda os cartões automáticos.

Galerinha, conseguem testar se podem visualizar os cards e mover eles entre as colunas?
https://github.com/aztecweb/lista-de-compras/projects/1

**Comment by mblithium** [comment]
> Adicionei as issues ao projeto, deixando ainda os cartões automáticos.
> 
> Galerinha, conseguem testar se podem visualizar os cards e mover eles entre as colunas? https://github.com/aztecweb/lista-de-compras/projects/1

Consigo visualizar e copiar o link dos cards, mas não mover eles.

**Comment by marcosvile** [comment]
> 

Consigo visualizar e copiar o link dos cards, mas não mover, criar ou alterar eles.

**Comment by mateusrovedaa** [comment]
@edpittol Não consegui alterar as permissões. Achei esse link que pode ser útil: https://docs.github.com/pt/organizations/managing-access-to-your-organizations-project-boards/project-board-permissions-for-an-organization

**Comment by mateusrovedaa** [comment]
Ficou definido que vamos ajustar o status das issues nos encontros, não precisando assim que outras pessoas tenham permissão para mover cards no quadro.
