### ISSUE TITLE
[Discussão]: Biblioteca/Framework para o front-end

### ISSUE THREAD

**Issue by mateusrovedaa** [aztecweb/lista-de-compras#34]
### Descrição

Com o passar do tempo desde a definição inicial do uso de React no front-end, faz-se necessária uma nova avaliação para verificar se devemos continuar utilizando React ou se outra ferramenta seria mais adequada para o projeto. Para garantir que a escolha seja a mais alinhada com os objetivos e desafios do projeto, propomos avaliar as seguintes opções:

1.  **React**: Atual ferramenta definida para o projeto. Componentes reutilizáveis e forte comunidade.
2.  **VueJS**: Framework leve com curva de aprendizado suave. 
3.  **Angular**: Framework robusto com funcionalidades completas nativas.

Para votar, use os emojis abaixo:
- React 🚀
- VueJS ❤️
- Angular 🎉

### Objetivo

Selecionar a ferramenta mais adequada para o desenvolvimento do front-end do projeto, levando em consideração:

1. Curva de aprendizado da comunidade.
2. Facilidade de contribuição para novos desenvolvedores.
3. Performance em aplicações de pequeno a médio porte.
4. Suporte e longevidade da ferramenta no ecossistema web.
5. Flexibilidade e escalabilidade para demandas futuras.

**Comment by mateusrovedaa** [comment]
Eu opino em mantermos o React. Algumas alterações foram feitas no projeto e agora o padrão para desenvolvimento com React é o [Next.JS](https://nextjs.org/), um framework interessante. Entretanto, sei que o ecossistema Vue é interessante por sua curva de aprendizado ser mais suave.

**Comment by mblithium** [comment]
Recentemente eu estava estudando um pouco de [Vue](https://vuejs.org) com [Nuxt](https://nuxt.com) por curiosidade, na minha opinião achei muito massa como ele funciona, ele é bem rápido e o [devtools](https://devtools.vuejs.org/getting-started/features) é muito doido. Mas para efeito de aprendizado, no contexto atual do projeto, acho melhor manter o **React/NextJS**, para todos os envolvidos focarem nessa tecnologia que é [mais popular](https://survey.stackoverflow.co/2024/technology#most-popular-technologies-webframe) que o Vue atualmente em desenvolvimento web profissional.

**Comment by marcosvile** [comment]
Me abstenho da votação por falta de knowhow.

**Comment by mateusrovedaa** [comment]
Definido React com NextJS e Storybook.
