### ISSUE TITLE
Definir a licença de uso do projeto 

### ISSUE THREAD

**Issue by mblithium** [aztecweb/lista-de-compras#9]
# Descrição
É muito importante definir uma licença de uso para que fique claro quais são as permissões que os desenvolvedores do projeto  querem definir aos utilizadores. 

# Objetivo
Discutir e definir uma licença para o projeto.

# Links úteis
- [Choose a license - Github](https://choosealicense.com/)
- [Tudo o que você precisa saber sobre as licenças de projetos open source](https://medium.com/trainingcenter/tudo-o-que-voc%C3%AA-precisa-saber-sobre-as-licen%C3%A7as-de-projetos-open-source-aaccbe23e50d)
- [5 types of software licenses you need to understand](https://www.synopsys.com/blogs/software-security/5-types-of-software-licenses-you-need-to-understand/)
- [Dicionário do Programador - Código Fonte TV - Licenças de Software](https://www.youtube.com/watch?v=fPfzp6ov2bQ)

**Comment by marcosvile** [comment]
Estive lendo sobre licenças, e pensei em sugerir a licença GNU GPLv3, li sobre esse tipo de licença em um própria referência do github https://choosealicense.com/licenses/gpl-3.0/

Pelo que pude compreender, a licença GPLv3, parece ter mais condições que remetem a informar/divulgar a fonte original, no caso o repositório original em caso de replicação, no caso o repositório da Aztec, acho um ponto positivo pois remete a uma divulgação.

**Comment by marlonpedro** [comment]
Fiz a leitura de algumas licenças que poderíamos utilizar e creio que a GNU GPLv3 se encaixa mais no nosso quesito.
Achei interessante que ela obriga a manter a licença do projeto.

**Comment by marcosvile** [comment]
O github tem um método facilitado para escolher a licença para projetos de uma forma mais automática, pela seguinte documentação:

https://docs.github.com/pt/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
